# Generated by Django 2.1.3 on 2018-11-25 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('first_app', '0002_auto_20181125_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('number', models.CharField(max_length=100)),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.doctor')),
            ],
        ),
    ]
