# Generated by Django 2.1.3 on 2018-11-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='doc_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
