# Generated by Django 2.1.3 on 2018-11-25 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_app', '0002_auto_20181125_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slots',
            name='doc_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.doctor'),
        ),
    ]
