# Generated by Django 2.1.3 on 2018-11-25 07:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_auto_20181125_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 11, 25, 12, 54, 4, 388817)),
        ),
    ]
