# Generated by Django 2.1.3 on 2018-11-25 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_auto_20181125_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 11, 25, 18, 47, 30, 231496)),
        ),
    ]
