# Generated by Django 2.1.3 on 2018-11-26 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_auto_20181125_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='start_time',
            field=models.TimeField(default='12:00'),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 11, 27, 1, 47, 40, 206851)),
        ),
    ]
